### ISSUE TITLE
spacing in declarations

### ISSUE THREAD

**Issue by Beliavsky** [OneOrdinaryMan/fortran-learner-repo#1]
It is a matter of taste, but I think it is easier to read declarations if there is a space before and after the `::`, so a declaration looks like

`integer :: i`

instead of

`integer::i`

Most modern Fortran code I see does use spaces around `::` in declarations.

**Comment by OneOrdinaryMan** [comment]
This is a mirror repository. Issue will be created in the original repository and fixed there. Once fixed there the issue will be closed.

- [x] Add spaces in declaration


To check original repo,
https://gitlab.com/One_Ordinary_Man/fortran-learner-repo
