### ISSUE TITLE
add topics

### ISSUE THREAD

**Issue by Beliavsky** [OneOrdinaryMan/fortran-learner-repo#2]
I suggest adding the topics `fortran`, `fortran-tutorial`, `modern-fortran` in the About section at https://github.com/OneOrdinaryMan/fortran-learner-repo , as described at https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics .

**Comment by OneOrdinaryMan** [comment]
- [x] Added short description in about.
- [x] Added the topics in about
